version: '2'
services:
  www:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    volumes: ['./www/:/opt/www'] # Code Reload
    command: python3 controller.py # Production Code: python3 wsgi.py
  db:
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
    restart: always
    ports: 
      - "3306:3306" # MySQL Port
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      # MYSQL_DATABASE: db_sfsp
      MYSQL_ROOT_PASSWORD: gcc@2k20~#
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080